<?php

if (!defined('ABSPATH')) {
   exit;
}

class ThemeOptionsRegister
{
   function __construct()
   {
      add_action('acf/init', [$this, 'register_parent_page']);
      add_action('acf/init', [$this, 'register_home_page']);
   }

   public function register_parent_page()
   {
      if (!function_exists('acf_add_options_page')) {
         return;
      }

      acf_add_options_page([
         'page_title' => __('Opções do Tema', 'thunay'),
         'menu_title' => __('Opções do tema', 'thunay'),
         'menu_slug'  => 'theme-options',
         'redirect'   => true,
         'position'   => 2,
      ]);
   }

   public function register_home_page()
   {
      if (!function_exists('acf_add_options_page')) {
         return;
      }

      acf_add_options_page([
         'page_title' => __('Home', 'thunay'),
         'menu_title' => __('Home', 'thunay'),
         'menu_slug' => 'theme-options-home',
         'parent_slug' => 'theme-options',
      ]);

      $this->register_home_hero();
      $this->register_home_about_me();
      $this->register_home_services();
      $this->register_home_skills();
      $this->register_home_experience();
   }

   private function register_home_hero()
   {
      if (!function_exists('acf_add_local_field_group')) {
         return;
      }

      acf_add_local_field_group([
         'key' => 'group_66566babb591b',
         'title' => __('Hero', 'thunay'),
         'fields' => [
            [
               'key' => 'field_66566f9e3d181',
               'label' => __('Título e descrição', 'thunay'),
               'name' => '',
               'aria-label' => '',
               'type' => 'tab',
               'instructions' => '',
               'required' => 0,
               'conditional_logic' => 0,
               'wrapper' => [
                  'width' => '',
                  'class' => '',
                  'id' => '',
               ],
               'placement' => 'top',
               'endpoint' => 0,
            ],
            [
               'key' => 'field_66566bcfd24ff',
               'label' => __('Título', 'thunay'),
               'name' => 'home_hero_title',
               'aria-label' => '',
               'type' => 'textarea',
               'instructions' => '',
               'required' => 0,
               'conditional_logic' => 0,
               'wrapper' => [
                  'width' => '',
                  'class' => '',
                  'id' => '',
               ],
               'default_value' => '',
               'maxlength' => '',
               'rows' => '',
               'placeholder' => __('Thunay Moreira de Soares', 'thunay'),
               'new_lines' => '',
            ],
            [
               'key' => 'field_66566e93288f2',
               'label' => __('Descrição', 'thunay'),
               'name' => 'home_hero_description',
               'aria-label' => '',
               'type' => 'textarea',
               'instructions' => '',
               'required' => 0,
               'conditional_logic' => 0,
               'wrapper' => [
                  'width' => '',
                  'class' => '',
                  'id' => '',
               ],
               'default_value' => '',
               'maxlength' => '',
               'rows' => '',
               'placeholder' => __('Desenvolvedor Fullstack', 'thunay'),
               'new_lines' => '',
            ],
            [
               'key' => 'field_66566fb93d182',
               'label' => __('Redes sociais', 'thunay'),
               'name' => '',
               'aria-label' => '',
               'type' => 'tab',
               'instructions' => '',
               'required' => 0,
               'conditional_logic' => 0,
               'wrapper' => [
                  'width' => '',
                  'class' => '',
                  'id' => '',
               ],
               'placement' => 'top',
               'endpoint' => 0,
            ],
            [
               'key' => 'field_66566fcc3d183',
               'label' => __('Github', 'thunay'),
               'name' => 'home_hero_github',
               'aria-label' => '',
               'type' => 'text',
               'instructions' => '',
               'required' => 0,
               'conditional_logic' => 0,
               'wrapper' => [
                  'width' => '',
                  'class' => '',
                  'id' => '',
               ],
               'default_value' => '',
               'maxlength' => '',
               'placeholder' => '',
               'prepend' => '',
               'append' => '',
            ],
            [
               'key' => 'field_66566fefd4a30',
               'label' => __('Linkedin', 'thunay'),
               'name' => 'home_hero_linkedin',
               'aria-label' => '',
               'type' => 'text',
               'instructions' => '',
               'required' => 0,
               'conditional_logic' => 0,
               'wrapper' => [
                  'width' => '',
                  'class' => '',
                  'id' => '',
               ],
               'default_value' => '',
               'maxlength' => '',
               'placeholder' => '',
               'prepend' => '',
               'append' => '',
            ],
            [
               'key' => 'field_66566ffbd4a31',
               'label' => __('E-mail', 'thunay'),
               'name' => 'home_hero_email',
               'aria-label' => '',
               'type' => 'text',
               'instructions' => '',
               'required' => 0,
               'conditional_logic' => 0,
               'wrapper' => [
                  'width' => '',
                  'class' => '',
                  'id' => '',
               ],
               'default_value' => '',
               'maxlength' => '',
               'placeholder' => '',
               'prepend' => '',
               'append' => '',
            ],
            [
               'key' => 'field_6656700ed4a32',
               'label' => __('Currículo', 'thunay'),
               'name' => 'home_hero_curriculum',
               'aria-label' => '',
               'type' => 'text',
               'instructions' => '',
               'required' => 0,
               'conditional_logic' => 0,
               'wrapper' => [
                  'width' => '',
                  'class' => '',
                  'id' => '',
               ],
               'default_value' => '',
               'maxlength' => '',
               'placeholder' => '',
               'prepend' => '',
               'append' => '',
            ],
            [
               'key' => 'field_6656701bd4a33',
               'label' => __('Whatsapp', 'thunay'),
               'name' => 'home_hero_whatsapp',
               'aria-label' => '',
               'type' => 'text',
               'instructions' => '',
               'required' => 0,
               'conditional_logic' => 0,
               'wrapper' => [
                  'width' => '',
                  'class' => '',
                  'id' => '',
               ],
               'default_value' => '',
               'maxlength' => '',
               'placeholder' => '',
               'prepend' => '',
               'append' => '',
            ],
            [
               'key' => 'field_665676efbf8d8',
               'label' => __('Imagem destacada', 'thunay'),
               'name' => '',
               'aria-label' => '',
               'type' => 'tab',
               'instructions' => '',
               'required' => 0,
               'conditional_logic' => 0,
               'wrapper' => [
                  'width' => '',
                  'class' => '',
                  'id' => '',
               ],
               'placement' => 'top',
               'endpoint' => 0,
            ],
            [
               'key' => 'field_665676be28d35',
               'label' => __('Imagem', 'thunay'),
               'name' => 'home_hero_featured_image',
               'aria-label' => '',
               'type' => 'image',
               'instructions' => '',
               'required' => 0,
               'conditional_logic' => 0,
               'wrapper' => [
                  'width' => '',
                  'class' => '',
                  'id' => '',
               ],
               'return_format' => 'url',
               'library' => 'all',
               'min_width' => '',
               'min_height' => '',
               'min_size' => '',
               'max_width' => '',
               'max_height' => '',
               'max_size' => '',
               'mime_types' => '',
               'preview_size' => 'medium',
            ],
         ],
         'location' => [
            [
               [
                  'param' => 'options_page',
                  'operator' => '==',
                  'value' => 'theme-options-home',
               ],
            ],
         ],
         'menu_order' => 0,
         'position' => 'normal',
         'style' => 'default',
         'label_placement' => 'top',
         'instruction_placement' => 'label',
         'hide_on_screen' => '',
         'active' => true,
         'description' => '',
         'show_in_rest' => 0,
      ]);
   }

   private function register_home_about_me()
   {
      if (!function_exists('acf_add_local_field_group')) {
         return;
      }

      acf_add_local_field_group([
         'key' => 'group_6663a610e17bd',
         'title' => __('Sobre mim', 'thunay'),
         'fields' => [
            [
               'key' => 'field_6663a611fcf32',
               'label' => __('Foto', 'thunay'),
               'name' => '',
               'aria-label' => '',
               'type' => 'tab',
               'instructions' => '',
               'required' => 0,
               'conditional_logic' => 0,
               'wrapper' => [
                  'width' => '',
                  'class' => '',
                  'id' => '',
               ],
               'placement' => 'top',
               'endpoint' => 0,
            ],
            [
               'key' => 'field_6663a64bfcf33',
               'label' => __('Foto', 'thunay'),
               'name' => 'home_about_me_photo',
               'aria-label' => '',
               'type' => 'image',
               'instructions' => '',
               'required' => 0,
               'conditional_logic' => 0,
               'wrapper' => [
                  'width' => '',
                  'class' => '',
                  'id' => '',
               ],
               'return_format' => 'array',
               'library' => 'all',
               'min_width' => '',
               'min_height' => '',
               'min_size' => '',
               'max_width' => '',
               'max_height' => '',
               'max_size' => '',
               'mime_types' => '',
               'preview_size' => 'medium',
            ],
            [
               'key' => 'field_6663a669fcf34',
               'label' => __('Informações', 'thunay'),
               'name' => '',
               'aria-label' => '',
               'type' => 'tab',
               'instructions' => '',
               'required' => 0,
               'conditional_logic' => 0,
               'wrapper' => [
                  'width' => '',
                  'class' => '',
                  'id' => '',
               ],
               'placement' => 'top',
               'endpoint' => 0,
            ],
            [
               'key' => 'field_6663a682fcf35',
               'label' => __('Nome', 'thunay'),
               'name' => 'home_about_me_name',
               'aria-label' => '',
               'type' => 'text',
               'instructions' => '',
               'required' => 0,
               'conditional_logic' => 0,
               'wrapper' => [
                  'width' => '',
                  'class' => '',
                  'id' => '',
               ],
               'default_value' => '',
               'maxlength' => '',
               'placeholder' => '',
               'prepend' => '',
               'append' => '',
            ],
            [
               'key' => 'field_6663a692fcf36',
               'label' => __('Cargo', 'thunay'),
               'name' => 'home_about_me_job',
               'aria-label' => '',
               'type' => 'text',
               'instructions' => '',
               'required' => 0,
               'conditional_logic' => 0,
               'wrapper' => [
                  'width' => '',
                  'class' => '',
                  'id' => '',
               ],
               'default_value' => '',
               'maxlength' => '',
               'placeholder' => '',
               'prepend' => '',
               'append' => '',
            ],
            [
               'key' => 'field_6663a6a1fcf37',
               'label' => __('Descrição', 'thunay'),
               'name' => 'home_about_me_description',
               'aria-label' => '',
               'type' => 'textarea',
               'instructions' => '',
               'required' => 0,
               'conditional_logic' => 0,
               'wrapper' => [
                  'width' => '',
                  'class' => '',
                  'id' => '',
               ],
               'default_value' => '',
               'maxlength' => '',
               'rows' => '',
               'placeholder' => '',
               'new_lines' => '',
            ],
         ],
         'location' => [
            [
               [
                  'param' => 'options_page',
                  'operator' => '==',
                  'value' => 'theme-options-home',
               ],
            ],
         ],
         'menu_order' => 0,
         'position' => 'normal',
         'style' => 'default',
         'label_placement' => 'top',
         'instruction_placement' => 'label',
         'hide_on_screen' => '',
         'active' => true,
         'description' => '',
         'show_in_rest' => 0,
      ]);
   }

   private function register_home_services()
   {
      if (!function_exists('acf_add_local_field_group')) {
         return;
      }

      acf_add_local_field_group([
         'key' => 'group_6668f7d156d3f',
         'title' => __('Serviços', 'thunay'),
         'fields' => [
            [
               'key' => 'field_6668f7d1b3ae2',
               'label' => __('Texto', 'thunay'),
               'name' => '',
               'aria-label' => '',
               'type' => 'tab',
               'instructions' => '',
               'required' => 0,
               'conditional_logic' => 0,
               'wrapper' => [
                  'width' => '',
                  'class' => '',
                  'id' => '',
               ],
               'placement' => 'top',
               'endpoint' => 0,
            ],
            [
               'key' => 'field_6668f82ab3ae3',
               'label' => __('Texto', 'thunay'),
               'name' => 'home_services_text',
               'aria-label' => '',
               'type' => 'repeater',
               'instructions' => '',
               'required' => 0,
               'conditional_logic' => 0,
               'wrapper' => [
                  'width' => '',
                  'class' => '',
                  'id' => '',
               ],
               'layout' => 'table',
               'pagination' => 0,
               'min' => 0,
               'max' => 0,
               'collapsed' => '',
               'button_label' => __('Adicionar Linha', 'thunay'),
               'rows_per_page' => 20,
               'sub_fields' => [
                  [
                     'key' => 'field_666b828c790de',
                     'label' => __('Parágrafo', 'thunay'),
                     'name' => 'paragraph',
                     'aria-label' => '',
                     'type' => 'textarea',
                     'instructions' => '',
                     'required' => 0,
                     'conditional_logic' => 0,
                     'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                     ],
                     'default_value' => '',
                     'maxlength' => '',
                     'rows' => '',
                     'placeholder' => '',
                     'new_lines' => '',
                     'parent_repeater' => 'field_6668f82ab3ae3',
                  ],
               ],
            ],
            [
               'key' => 'field_6668f867b3ae5',
               'label' => __('Cards', 'thunay'),
               'name' => '',
               'aria-label' => '',
               'type' => 'tab',
               'instructions' => '',
               'required' => 0,
               'conditional_logic' => 0,
               'wrapper' => [
                  'width' => '',
                  'class' => '',
                  'id' => '',
               ],
               'placement' => 'top',
               'endpoint' => 0,
            ],
            [
               'key' => 'field_6668f885b3ae6',
               'label' => __('Cards', 'thunay'),
               'name' => 'home_services_cards',
               'aria-label' => '',
               'type' => 'repeater',
               'instructions' => '',
               'required' => 0,
               'conditional_logic' => 0,
               'wrapper' => [
                  'width' => '',
                  'class' => '',
                  'id' => '',
               ],
               'layout' => 'table',
               'pagination' => 0,
               'min' => 0,
               'max' => 0,
               'collapsed' => '',
               'button_label' => __('Adicionar Linha', 'thunay'),
               'rows_per_page' => 20,
               'sub_fields' => [
                  [
                     'key' => 'field_6668f89db3ae7',
                     'label' => __('Imagem', 'thunay'),
                     'name' => 'image',
                     'aria-label' => '',
                     'type' => 'image',
                     'instructions' => '',
                     'required' => 0,
                     'conditional_logic' => 0,
                     'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                     ],
                     'return_format' => 'array',
                     'library' => 'all',
                     'min_width' => '',
                     'min_height' => '',
                     'min_size' => '',
                     'max_width' => '',
                     'max_height' => '',
                     'max_size' => '',
                     'mime_types' => '',
                     'preview_size' => 'medium',
                     'parent_repeater' => 'field_6668f885b3ae6',
                  ],
                  [
                     'key' => 'field_6668f8b2b3ae8',
                     'label' => __('Título', 'thunay'),
                     'name' => 'title',
                     'aria-label' => '',
                     'type' => 'text',
                     'instructions' => '',
                     'required' => 0,
                     'conditional_logic' => 0,
                     'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                     ],
                     'default_value' => '',
                     'maxlength' => '',
                     'placeholder' => '',
                     'prepend' => '',
                     'append' => '',
                     'parent_repeater' => 'field_6668f885b3ae6',
                  ],
                  [
                     'key' => 'field_6668f8beb3ae9',
                     'label' => __('Descrição', 'thunay'),
                     'name' => 'description',
                     'aria-label' => '',
                     'type' => 'textarea',
                     'instructions' => '',
                     'required' => 0,
                     'conditional_logic' => 0,
                     'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                     ],
                     'default_value' => '',
                     'maxlength' => '',
                     'rows' => '',
                     'placeholder' => '',
                     'new_lines' => '',
                     'parent_repeater' => 'field_6668f885b3ae6',
                  ],
               ],
            ],
         ],
         'location' => [
            [
               [
                  'param' => 'options_page',
                  'operator' => '==',
                  'value' => 'theme-options-home',
               ],
            ],
         ],
         'menu_order' => 0,
         'position' => 'normal',
         'style' => 'default',
         'label_placement' => 'top',
         'instruction_placement' => 'label',
         'hide_on_screen' => '',
         'active' => true,
         'description' => '',
         'show_in_rest' => 0,
      ]);
   }

   private function register_home_skills()
   {
      if (! function_exists('acf_add_local_field_group')) {
         return;
      }

      acf_add_local_field_group([
         'key' => 'group_6672a40402c31',
         'title' => __('Habilidades', 'thunay'),
         'fields' => [
            [
               'key' => 'field_6672a43fc8208',
               'label' => __('Texto', 'thunay'),
               'name' => '',
               'aria-label' => '',
               'type' => 'tab',
               'instructions' => '',
               'required' => 0,
               'conditional_logic' => 0,
               'wrapper' => [
                  'width' => '',
                  'class' => '',
                  'id' => '',
               ],
               'placement' => 'top',
               'endpoint' => 0,
            ],
            [
               'key' => 'field_6672a404c8207',
               'label' => __('Descrição', 'thunay'),
               'name' => 'home_skills_description',
               'aria-label' => '',
               'type' => 'textarea',
               'instructions' => '',
               'required' => 0,
               'conditional_logic' => 0,
               'wrapper' => [
                  'width' => '',
                  'class' => '',
                  'id' => '',
               ],
               'default_value' => '',
               'maxlength' => '',
               'rows' => '',
               'placeholder' => '',
               'new_lines' => '',
            ],
            [
               'key' => 'field_6672a452c8209',
               'label' => __('Habilidades', 'thunay'),
               'name' => '',
               'aria-label' => '',
               'type' => 'tab',
               'instructions' => '',
               'required' => 0,
               'conditional_logic' => 0,
               'wrapper' => [
                  'width' => '',
                  'class' => '',
                  'id' => '',
               ],
               'placement' => 'top',
               'endpoint' => 0,
            ],
            [
               'key' => 'field_6672a466c820a',
               'label' => __('Lista de habilidades', 'thunay'),
               'name' => 'home_skills_skills_list',
               'aria-label' => '',
               'type' => 'repeater',
               'instructions' => '',
               'required' => 0,
               'conditional_logic' => 0,
               'wrapper' => [
                  'width' => '',
                  'class' => '',
                  'id' => '',
               ],
               'layout' => 'table',
               'pagination' => 0,
               'min' => 0,
               'max' => 0,
               'collapsed' => '',
               'button_label' => __('Adicionar Habilidade', 'thunay'),
               'rows_per_page' => 20,
               'sub_fields' => [
                  [
                     'key' => 'field_6672a48dc820b',
                     'label' => __('Nome', 'thunay'),
                     'name' => 'name',
                     'aria-label' => '',
                     'type' => 'text',
                     'instructions' => '',
                     'required' => 0,
                     'conditional_logic' => 0,
                     'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                     ],
                     'default_value' => '',
                     'maxlength' => '',
                     'placeholder' => '',
                     'prepend' => '',
                     'append' => '',
                     'parent_repeater' => 'field_6672a466c820a',
                  ],
                  [
                     'key' => 'field_6672a49ac820c',
                     'label' => __('Porcentagem', 'thunay'),
                     'name' => 'percent',
                     'aria-label' => '',
                     'type' => 'range',
                     'instructions' => '',
                     'required' => 0,
                     'conditional_logic' => 0,
                     'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                     ],
                     'default_value' => '',
                     'min' => '',
                     'max' => '',
                     'step' => '',
                     'prepend' => '',
                     'append' => '%',
                     'parent_repeater' => 'field_6672a466c820a',
                  ],
               ],
            ],
         ],
         'location' => [
            [
               [
                  'param' => 'options_page',
                  'operator' => '==',
                  'value' => 'theme-options-home',
               ],
            ],
         ],
         'menu_order' => 0,
         'position' => 'normal',
         'style' => 'default',
         'label_placement' => 'top',
         'instruction_placement' => 'label',
         'hide_on_screen' => '',
         'active' => true,
         'description' => '',
         'show_in_rest' => 0,
      ]);
   }

   private function register_home_experience()
   {
      if (! function_exists('acf_add_local_field_group')) {
         return;
      }

      acf_add_local_field_group([
         'key' => 'group_6674d37fa8b07',
         'title' => __('Experiência', 'thunay'),
         'fields' => [
            [
               'key' => 'field_6674d37f8cb57',
               'label' => __('Texto', 'thunay'),
               'name' => '',
               'aria-label' => '',
               'type' => 'tab',
               'instructions' => '',
               'required' => 0,
               'conditional_logic' => 0,
               'wrapper' => [
                  'width' => '',
                  'class' => '',
                  'id' => '',
               ],
               'placement' => 'top',
               'endpoint' => 0,
            ],
            [
               'key' => 'field_6674d39a8cb58',
               'label' => __('Descrição', 'thunay'),
               'name' => 'home_experience_text',
               'aria-label' => '',
               'type' => 'textarea',
               'instructions' => '',
               'required' => 0,
               'conditional_logic' => 0,
               'wrapper' => [
                  'width' => '',
                  'class' => '',
                  'id' => '',
               ],
               'default_value' => '',
               'maxlength' => '',
               'rows' => '',
               'placeholder' => '',
               'new_lines' => '',
            ],
            [
               'key' => 'field_6674d3c58cb59',
               'label' => __('Experiência', 'thunay'),
               'name' => '',
               'aria-label' => '',
               'type' => 'tab',
               'instructions' => '',
               'required' => 0,
               'conditional_logic' => 0,
               'wrapper' => [
                  'width' => '',
                  'class' => '',
                  'id' => '',
               ],
               'placement' => 'top',
               'endpoint' => 0,
            ],
            [
               'key' => 'field_6674d3dd8cb5a',
               'label' => __('Timeline', 'thunay'),
               'name' => 'home_experience_timeline',
               'aria-label' => '',
               'type' => 'repeater',
               'instructions' => '',
               'required' => 0,
               'conditional_logic' => 0,
               'wrapper' => [
                  'width' => '',
                  'class' => '',
                  'id' => '',
               ],
               'layout' => 'table',
               'pagination' => 0,
               'min' => 0,
               'max' => 0,
               'collapsed' => '',
               'button_label' => __('Adicionar Experiência', 'thunay'),
               'rows_per_page' => 20,
               'sub_fields' => [
                  [
                     'key' => 'field_6674d3f28cb5b',
                     'label' => __('Profissão', 'thunay'),
                     'name' => 'profission',
                     'aria-label' => '',
                     'type' => 'text',
                     'instructions' => '',
                     'required' => 0,
                     'conditional_logic' => 0,
                     'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                     ],
                     'default_value' => '',
                     'maxlength' => '',
                     'placeholder' => '',
                     'prepend' => '',
                     'append' => '',
                     'parent_repeater' => 'field_6674d3dd8cb5a',
                  ],
                  [
                     'key' => 'field_6674d4148cb5c',
                     'label' => __('Empresa', 'thunay'),
                     'name' => 'company',
                     'aria-label' => '',
                     'type' => 'text',
                     'instructions' => '',
                     'required' => 0,
                     'conditional_logic' => 0,
                     'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                     ],
                     'default_value' => '',
                     'maxlength' => '',
                     'placeholder' => '',
                     'prepend' => '',
                     'append' => '',
                     'parent_repeater' => 'field_6674d3dd8cb5a',
                  ],
                  [
                     'key' => 'field_6674d42e8cb5d',
                     'label' => __('Tempo de experiência', 'thunay'),
                     'name' => 'experience_time',
                     'aria-label' => '',
                     'type' => 'text',
                     'instructions' => '',
                     'required' => 0,
                     'conditional_logic' => 0,
                     'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                     ],
                     'default_value' => '',
                     'maxlength' => '',
                     'placeholder' => '',
                     'prepend' => '',
                     'append' => '',
                     'parent_repeater' => 'field_6674d3dd8cb5a',
                  ],
                  [
                     'key' => 'field_6674d4488cb5e',
                     'label' => __('Descrição do trabalho', 'thunay'),
                     'name' => 'job_description',
                     'aria-label' => '',
                     'type' => 'textarea',
                     'instructions' => '',
                     'required' => 0,
                     'conditional_logic' => 0,
                     'wrapper' => [
                        'width' => '',
                        'class' => '',
                        'id' => '',
                     ],
                     'default_value' => '',
                     'maxlength' => '',
                     'rows' => '',
                     'placeholder' => '',
                     'new_lines' => '',
                     'parent_repeater' => 'field_6674d3dd8cb5a',
                  ],
               ],
            ],
         ],
         'location' => [
            [
               [
                  'param' => 'options_page',
                  'operator' => '==',
                  'value' => 'theme-options-home',
               ],
            ],
         ],
         'menu_order' => 0,
         'position' => 'normal',
         'style' => 'default',
         'label_placement' => 'top',
         'instruction_placement' => 'label',
         'hide_on_screen' => '',
         'active' => true,
         'description' => '',
         'show_in_rest' => 0,
      ]);
   }
}

new ThemeOptionsRegister();
